/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Alejandro
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Desktop = new javax.swing.JDesktopPane();
        jToolBar1 = new javax.swing.JToolBar();
        btnConductores = new javax.swing.JButton();
        btnVehiculos = new javax.swing.JButton();
        btnTransportes = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuConductores = new javax.swing.JMenuItem();
        jMenuVehiculos = new javax.swing.JMenuItem();
        jMenuTransportes = new javax.swing.JMenuItem();
        jMenuSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuParalelo = new javax.swing.JMenuItem();
        jMenuCascada = new javax.swing.JMenuItem();
        jMenuCerrarActual = new javax.swing.JMenuItem();
        jMenuCerrarTodas = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuContenido = new javax.swing.JMenuItem();
        jMenuAcercade = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 612, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );

        jToolBar1.setRollover(true);

        btnConductores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/driver.png"))); // NOI18N
        btnConductores.setFocusable(false);
        btnConductores.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConductores.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnConductores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConductoresActionPerformed(evt);
            }
        });
        jToolBar1.add(btnConductores);

        btnVehiculos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/vehicle.png"))); // NOI18N
        btnVehiculos.setFocusable(false);
        btnVehiculos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVehiculos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVehiculosActionPerformed(evt);
            }
        });
        jToolBar1.add(btnVehiculos);

        btnTransportes.setText("Transportes");
        btnTransportes.setFocusable(false);
        btnTransportes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTransportes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTransportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransportesActionPerformed(evt);
            }
        });
        jToolBar1.add(btnTransportes);

        btnSalir.setText("Salir");
        btnSalir.setFocusable(false);
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnSalir);

        jMenu1.setText("Archivo");

        jMenuConductores.setText("Conductores");
        jMenuConductores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuConductoresActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuConductores);

        jMenuVehiculos.setText("Vehiculos");
        jMenuVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuVehiculosActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuVehiculos);

        jMenuTransportes.setText("Transportes");
        jMenuTransportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuTransportesActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuTransportes);

        jMenuSalir.setText("Salir");
        jMenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSalirActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ventanas");

        jMenuParalelo.setText("En Paralelo");
        jMenu2.add(jMenuParalelo);

        jMenuCascada.setText("En Cascada");
        jMenuCascada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCascadaActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuCascada);

        jMenuCerrarActual.setText("Cerrar Actual");
        jMenu2.add(jMenuCerrarActual);

        jMenuCerrarTodas.setText("Cerrar Todos");
        jMenu2.add(jMenuCerrarTodas);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ayuda");

        jMenuContenido.setText("Contenido");
        jMenu3.add(jMenuContenido);

        jMenuAcercade.setText("Acerca de...");
        jMenu3.add(jMenuAcercade);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Desktop))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConductoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConductoresActionPerformed
        frmDrivers win = new frmDrivers();
        Desktop.add(win);
        win.setVisible(true);
    }//GEN-LAST:event_btnConductoresActionPerformed

    private void jMenuTransportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuTransportesActionPerformed
        frmTransports win = new frmTransports();
        Desktop.add(win);
        win.setVisible(true);
    }//GEN-LAST:event_jMenuTransportesActionPerformed

    private void jMenuCascadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCascadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuCascadaActionPerformed

    private void jMenuVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuVehiculosActionPerformed
        frmVehicules win = new frmVehicules();
        Desktop.add(win);
        win.setVisible(true);
    }//GEN-LAST:event_jMenuVehiculosActionPerformed

    private void jMenuConductoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuConductoresActionPerformed
        frmDrivers win = new frmDrivers();
        Desktop.add(win);
        win.setVisible(true);
    }//GEN-LAST:event_jMenuConductoresActionPerformed

    private void jMenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSalirActionPerformed
       
    }//GEN-LAST:event_jMenuSalirActionPerformed

    private void btnTransportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransportesActionPerformed
        frmTransports win = new frmTransports();
        Desktop.add(win);
        win.setVisible(true);
    }//GEN-LAST:event_btnTransportesActionPerformed

    private void btnVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVehiculosActionPerformed
        frmVehicules win = new frmVehicules();
        Desktop.add(win);
        win.setVisible(true);
    }//GEN-LAST:event_btnVehiculosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JButton btnConductores;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnTransportes;
    private javax.swing.JButton btnVehiculos;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem jMenuAcercade;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCascada;
    private javax.swing.JMenuItem jMenuCerrarActual;
    private javax.swing.JMenuItem jMenuCerrarTodas;
    private javax.swing.JMenuItem jMenuConductores;
    private javax.swing.JMenuItem jMenuContenido;
    private javax.swing.JMenuItem jMenuParalelo;
    private javax.swing.JMenuItem jMenuSalir;
    private javax.swing.JMenuItem jMenuTransportes;
    private javax.swing.JMenuItem jMenuVehiculos;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("img/travel.png"));

        return retValue;
    }
}
